version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules # garante que a pasta node_modules existe sempre dentro do container e não é referencia
      - .:/home/node/app # mapeia todas as pastas locais com a pasta /app dentro do container.
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
  
